### PR TITLE
6.3 / API 8

### PR DESCRIPTION
**Pull request by ellieglad**
Changes:
- Updates FFXIVClientStructs
- Update ActionResourceSig
- Remove devPlugins for output dir as it's deprecated.

Goal:
- Initial support of 6.3 and API 8 with the new FFXIVClientStructs. Does not attempt to improve or clean up existing code aside from the minimal edits needed.

### CODE REVIEW

**Comment by rootdarkarchon** [comment]
For what it's worth, from my testing today this appears to be stable and without crashes.

**Comment by erickt420** [comment]
Hi Ellie thanks for making this change. Since the official repo hasn't merge yet, is there a simple way I can switch to this version until your change is merged?

**Comment by GnawtyVeritech** [comment]
> Hi Ellie thanks for making this change. Since the official repo hasn't merged yet, is there a simple way I can switch to this version until your change is merged?

Ellie has compiled her own version that you can access from her GitHub page. It needs to be downloaded locally and run as a developer plugin, until the official version is updated and you can then disable/remove the local dev version.

**Comment by wirchtalksgames** [comment]
Can you give a quick rundown of how to do this for a layman? I tried downloading the zip in Ellie's github, adding it to a folder and pointed Dalamud to its location via the "plugin dev" directory but it's not picking it up. I'm not sure if I downloaded the wrong files or pointed to the wrong folder.

**Comment by erickt420** [comment]
You need to compile the .dll with the .NET 7.0 SDK using Visual Studio 22 (free). Then you add a dev plugin location in the dalamud settings pointing to the .dll.

**Comment by ellieglad** [comment]
Happy to help! Hope you feel better soon 😄

**Pull request merged**
